repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
    -   id: isort
        additional_dependencies: ['isort==5.6.4']  # Specify the isort version you want to use

-   repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.0
    hooks:
    -   id: djlint-django
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'
    hooks:
    -   id: poetry-export
        args: [
            "-f", "requirements.txt",
            "-o", "requirements.txt",
            "--without-hashes"
        ]
