# Generated by Django 4.2.7 on 2023-11-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("cart", "0002_remove_cartitem_user_cartitem_saved_for_later_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_line",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="product.productline"),
        ),
    ]
